name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for letting us know! We look in to new issues as quickly as we can, but some of them are not always easy to solve, or even valid. Please understand if we close this after reviewing it.'
        pr-message: 'Thanks for contributing to the project! Someone will be along in the near future to make sure you are all set up for contributions.'
